<?xml version="1.0" encoding="utf-8"?><Database Name="campusweb" Class="CampuswebDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\campusweb.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.course" Member="courses">
    <Type Name="course">
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="c_code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="c_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="c_credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="course_course_offered" Member="course_offereds" ThisKey="c_id" OtherKey="c_id" Type="course_offered" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="u_name" Type="System.String" DbType="VarChar(45) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="u_password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="u_level" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Association Name="user_profile" Member="profiles" ThisKey="u_name" OtherKey="u_name" Type="profile" />
      <Association Name="user_section" Member="sections" ThisKey="u_name" OtherKey="u_name" Type="section" />
      <Association Name="user_section_student" Member="section_students" ThisKey="u_name" OtherKey="u_name" Type="section_student" />
      <Association Name="user_student_mark" Member="student_marks" ThisKey="u_name" OtherKey="u_name" Type="student_mark" />
    </Type>
  </Table>
  <Table Name="dbo.course_offered" Member="course_offereds">
    <Type Name="course_offered">
      <Column Name="co_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="course_offered_section" Member="sections" ThisKey="co_id" OtherKey="co_id" Type="section" />
      <Association Name="course_course_offered" Member="course" ThisKey="c_id" OtherKey="c_id" Type="course" IsForeignKey="true" />
      <Association Name="semester_course_offered" Member="semester" ThisKey="s_id" OtherKey="s_id" Type="semester" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.profile" Member="profiles">
    <Type Name="profile">
      <Column Name="u_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="p_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="p_phone_no" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="p_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="user_profile" Member="user" ThisKey="u_name" OtherKey="u_name" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.section" Member="sections">
    <Type Name="section">
      <Column Name="sec_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="co_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sec_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Association Name="course_offered_section" Member="course_offered" ThisKey="co_id" OtherKey="co_id" Type="course_offered" IsForeignKey="true" />
      <Association Name="user_section" Member="user" ThisKey="u_name" OtherKey="u_name" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.section_mark" Member="section_marks">
    <Type Name="section_mark">
      <Column Name="sm_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sec_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sm_item" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="sm_total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="sm_percentage" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="section_mark_student_mark" Member="student_marks" ThisKey="sm_id" OtherKey="sm_id" Type="student_mark" />
    </Type>
  </Table>
  <Table Name="dbo.section_student" Member="section_students">
    <Type Name="section_student">
      <Column Name="sec_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Association Name="user_section_student" Member="user" ThisKey="u_name" OtherKey="u_name" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.semester" Member="semesters">
    <Type Name="semester">
      <Column Name="s_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="s_year" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="s_sem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="semester_course_offered" Member="course_offereds" ThisKey="s_id" OtherKey="s_id" Type="course_offered" />
    </Type>
  </Table>
  <Table Name="dbo.student_mark" Member="student_marks">
    <Type Name="student_mark">
      <Column Name="u_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="sm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stum_score" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="section_mark_student_mark" Member="section_mark" ThisKey="sm_id" OtherKey="sm_id" Type="section_mark" IsForeignKey="true" />
      <Association Name="user_student_mark" Member="user" ThisKey="u_name" OtherKey="u_name" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteCourseOffered" Method="DeleteCourseOffered">
    <Parameter Name="co_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSection" Method="UpdateSection">
    <Parameter Name="sec_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="co_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="sec_no" Type="System.Int32" DbType="Int" />
    <Parameter Name="u_name" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteSection" Method="DeleteSection">
    <Parameter Name="sec_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertCourseOffered" Method="InsertCourseOffered">
    <Parameter Name="s_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="c_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertSection" Method="InsertSection">
    <Parameter Name="co_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="sec_no" Type="System.Int32" DbType="Int" />
    <Parameter Name="u_name" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertSectionStudent" Method="InsertSectionStudent">
    <Parameter Name="u_name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="sec_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SelectCourseOffered" Method="SelectCourseOffered">
    <ElementType Name="SelectCourseOfferedResult">
      <Column Name="display_name" Type="System.String" DbType="VarChar(266)" CanBeNull="true" />
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="c_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="c_credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="co_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_year" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="s_sem" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectSection" Method="SelectSection">
    <ElementType Name="SelectSectionResult">
      <Column Name="display_name" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sec_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="co_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sec_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="co_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="c_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="c_credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="s_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_year" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="s_sem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="u_name1" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="p_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="p_phone_no" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="p_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectSectionWithCourseOffered" Method="SelectSectionWithCourseOffered">
    <Parameter Name="co_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectSectionWithCourseOfferedResult">
      <Column Name="display_name" Type="System.String" DbType="VarChar(277)" CanBeNull="true" />
      <Column Name="sec_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="co_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sec_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="co_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="c_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="c_credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="s_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_year" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="s_sem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="u_name1" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="p_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="p_phone_no" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="p_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectSectionWithCourseOfferedAndStudent" Method="SelectSectionWithCourseOfferedAndStudent">
    <Parameter Name="co_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="u_name" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SelectSectionWithCourseOfferedAndStudentResult">
      <Column Name="taken" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="display_name" Type="System.String" DbType="VarChar(277)" CanBeNull="true" />
      <Column Name="sec_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="co_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sec_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="co_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="c_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="c_credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="s_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_year" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="s_sem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="u_name1" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="p_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="p_phone_no" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="p_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectStudentMarkWithStudentID" Method="SelectStudentMarkWithStudentID">
    <Parameter Name="u_name" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SelectStudentMarkWithStudentIDResult">
      <Column Name="u_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="sm_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stum_score" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="u_name1" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="p_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="p_phone_no" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="p_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="sm_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sec_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sm_item" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="sm_total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="sm_percentage" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="sec_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="co_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sec_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_name2" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="co_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="c_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="c_credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateCourseOffered" Method="UpdateCourseOffered">
    <Parameter Name="s_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="c_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="co_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>