#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="campusweb")]
	public partial class CampuswebDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcourse(course instance);
    partial void Updatecourse(course instance);
    partial void Deletecourse(course instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertcourse_offered(course_offered instance);
    partial void Updatecourse_offered(course_offered instance);
    partial void Deletecourse_offered(course_offered instance);
    partial void Insertsection(section instance);
    partial void Updatesection(section instance);
    partial void Deletesection(section instance);
    partial void Insertsection_mark(section_mark instance);
    partial void Updatesection_mark(section_mark instance);
    partial void Deletesection_mark(section_mark instance);
    partial void Insertsemester(semester instance);
    partial void Updatesemester(semester instance);
    partial void Deletesemester(semester instance);
    #endregion
		
		public CampuswebDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CampuswebDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CampuswebDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CampuswebDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CampuswebDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<course> courses
		{
			get
			{
				return this.GetTable<course>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<course_offered> course_offereds
		{
			get
			{
				return this.GetTable<course_offered>();
			}
		}
		
		public System.Data.Linq.Table<profile> profiles
		{
			get
			{
				return this.GetTable<profile>();
			}
		}
		
		public System.Data.Linq.Table<section> sections
		{
			get
			{
				return this.GetTable<section>();
			}
		}
		
		public System.Data.Linq.Table<section_mark> section_marks
		{
			get
			{
				return this.GetTable<section_mark>();
			}
		}
		
		public System.Data.Linq.Table<section_student> section_students
		{
			get
			{
				return this.GetTable<section_student>();
			}
		}
		
		public System.Data.Linq.Table<semester> semesters
		{
			get
			{
				return this.GetTable<semester>();
			}
		}
		
		public System.Data.Linq.Table<student_mark> student_marks
		{
			get
			{
				return this.GetTable<student_mark>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteCourseOffered")]
		public int DeleteCourseOffered([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> co_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), co_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateSection")]
		public int UpdateSection([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sec_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> co_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sec_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string u_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sec_id, co_id, sec_no, u_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteSection")]
		public int DeleteSection([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sec_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sec_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertCourseOffered")]
		public int InsertCourseOffered([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> s_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> c_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_id, c_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertSection")]
		public int InsertSection([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> co_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sec_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string u_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), co_id, sec_no, u_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectSection")]
		public ISingleResult<SelectSectionResult> SelectSection()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SelectSectionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateCourseOffered")]
		public int UpdateCourseOffered([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> s_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> c_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> co_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), s_id, c_id, co_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectCourseOffered")]
		public ISingleResult<SelectCourseOfferedResult> SelectCourseOffered()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SelectCourseOfferedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectSectionWithCourseOffered")]
		public ISingleResult<SelectSectionWithCourseOfferedResult> SelectSectionWithCourseOffered([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> co_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), co_id);
			return ((ISingleResult<SelectSectionWithCourseOfferedResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.course")]
	public partial class course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _c_id;
		
		private string _c_code;
		
		private string _c_name;
		
		private System.Nullable<int> _c_credit;
		
		private EntitySet<course_offered> _course_offereds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onc_idChanging(int value);
    partial void Onc_idChanged();
    partial void Onc_codeChanging(string value);
    partial void Onc_codeChanged();
    partial void Onc_nameChanging(string value);
    partial void Onc_nameChanged();
    partial void Onc_creditChanging(System.Nullable<int> value);
    partial void Onc_creditChanged();
    #endregion
		
		public course()
		{
			this._course_offereds = new EntitySet<course_offered>(new Action<course_offered>(this.attach_course_offereds), new Action<course_offered>(this.detach_course_offereds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					this.Onc_idChanging(value);
					this.SendPropertyChanging();
					this._c_id = value;
					this.SendPropertyChanged("c_id");
					this.Onc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_code", DbType="VarChar(10)")]
		public string c_code
		{
			get
			{
				return this._c_code;
			}
			set
			{
				if ((this._c_code != value))
				{
					this.Onc_codeChanging(value);
					this.SendPropertyChanging();
					this._c_code = value;
					this.SendPropertyChanged("c_code");
					this.Onc_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="VarChar(255)")]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this.Onc_nameChanging(value);
					this.SendPropertyChanging();
					this._c_name = value;
					this.SendPropertyChanged("c_name");
					this.Onc_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_credit", DbType="Int")]
		public System.Nullable<int> c_credit
		{
			get
			{
				return this._c_credit;
			}
			set
			{
				if ((this._c_credit != value))
				{
					this.Onc_creditChanging(value);
					this.SendPropertyChanging();
					this._c_credit = value;
					this.SendPropertyChanged("c_credit");
					this.Onc_creditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_course_offered", Storage="_course_offereds", ThisKey="c_id", OtherKey="c_id")]
		public EntitySet<course_offered> course_offereds
		{
			get
			{
				return this._course_offereds;
			}
			set
			{
				this._course_offereds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_course_offereds(course_offered entity)
		{
			this.SendPropertyChanging();
			entity.course = this;
		}
		
		private void detach_course_offereds(course_offered entity)
		{
			this.SendPropertyChanging();
			entity.course = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _u_name;
		
		private string _u_password;
		
		private string _u_level;
		
		private EntitySet<section> _sections;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onu_nameChanging(string value);
    partial void Onu_nameChanged();
    partial void Onu_passwordChanging(string value);
    partial void Onu_passwordChanged();
    partial void Onu_levelChanging(string value);
    partial void Onu_levelChanged();
    #endregion
		
		public user()
		{
			this._sections = new EntitySet<section>(new Action<section>(this.attach_sections), new Action<section>(this.detach_sections));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this.Onu_nameChanging(value);
					this.SendPropertyChanging();
					this._u_name = value;
					this.SendPropertyChanged("u_name");
					this.Onu_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string u_password
		{
			get
			{
				return this._u_password;
			}
			set
			{
				if ((this._u_password != value))
				{
					this.Onu_passwordChanging(value);
					this.SendPropertyChanging();
					this._u_password = value;
					this.SendPropertyChanged("u_password");
					this.Onu_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_level", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_level
		{
			get
			{
				return this._u_level;
			}
			set
			{
				if ((this._u_level != value))
				{
					this.Onu_levelChanging(value);
					this.SendPropertyChanging();
					this._u_level = value;
					this.SendPropertyChanged("u_level");
					this.Onu_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_section", Storage="_sections", ThisKey="u_name", OtherKey="u_name")]
		public EntitySet<section> sections
		{
			get
			{
				return this._sections;
			}
			set
			{
				this._sections.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sections(section entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_sections(section entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.course_offered")]
	public partial class course_offered : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _co_id;
		
		private int _c_id;
		
		private int _s_id;
		
		private EntitySet<section> _sections;
		
		private EntityRef<course> _course;
		
		private EntityRef<semester> _semester;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onco_idChanging(int value);
    partial void Onco_idChanged();
    partial void Onc_idChanging(int value);
    partial void Onc_idChanged();
    partial void Ons_idChanging(int value);
    partial void Ons_idChanged();
    #endregion
		
		public course_offered()
		{
			this._sections = new EntitySet<section>(new Action<section>(this.attach_sections), new Action<section>(this.detach_sections));
			this._course = default(EntityRef<course>);
			this._semester = default(EntityRef<semester>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int co_id
		{
			get
			{
				return this._co_id;
			}
			set
			{
				if ((this._co_id != value))
				{
					this.Onco_idChanging(value);
					this.SendPropertyChanging();
					this._co_id = value;
					this.SendPropertyChanged("co_id");
					this.Onco_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int NOT NULL")]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					if (this._course.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onc_idChanging(value);
					this.SendPropertyChanging();
					this._c_id = value;
					this.SendPropertyChanged("c_id");
					this.Onc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id", DbType="Int NOT NULL")]
		public int s_id
		{
			get
			{
				return this._s_id;
			}
			set
			{
				if ((this._s_id != value))
				{
					if (this._semester.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ons_idChanging(value);
					this.SendPropertyChanging();
					this._s_id = value;
					this.SendPropertyChanged("s_id");
					this.Ons_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_offered_section", Storage="_sections", ThisKey="co_id", OtherKey="co_id")]
		public EntitySet<section> sections
		{
			get
			{
				return this._sections;
			}
			set
			{
				this._sections.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_course_offered", Storage="_course", ThisKey="c_id", OtherKey="c_id", IsForeignKey=true)]
		public course course
		{
			get
			{
				return this._course.Entity;
			}
			set
			{
				course previousValue = this._course.Entity;
				if (((previousValue != value) 
							|| (this._course.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._course.Entity = null;
						previousValue.course_offereds.Remove(this);
					}
					this._course.Entity = value;
					if ((value != null))
					{
						value.course_offereds.Add(this);
						this._c_id = value.c_id;
					}
					else
					{
						this._c_id = default(int);
					}
					this.SendPropertyChanged("course");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="semester_course_offered", Storage="_semester", ThisKey="s_id", OtherKey="s_id", IsForeignKey=true)]
		public semester semester
		{
			get
			{
				return this._semester.Entity;
			}
			set
			{
				semester previousValue = this._semester.Entity;
				if (((previousValue != value) 
							|| (this._semester.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._semester.Entity = null;
						previousValue.course_offereds.Remove(this);
					}
					this._semester.Entity = value;
					if ((value != null))
					{
						value.course_offereds.Add(this);
						this._s_id = value.s_id;
					}
					else
					{
						this._s_id = default(int);
					}
					this.SendPropertyChanged("semester");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sections(section entity)
		{
			this.SendPropertyChanging();
			entity.course_offered = this;
		}
		
		private void detach_sections(section entity)
		{
			this.SendPropertyChanging();
			entity.course_offered = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.profile")]
	public partial class profile
	{
		
		private string _u_name;
		
		private string _p_name;
		
		private string _p_phone_no;
		
		private string _p_email;
		
		public profile()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this._u_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string p_name
		{
			get
			{
				return this._p_name;
			}
			set
			{
				if ((this._p_name != value))
				{
					this._p_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_phone_no", DbType="VarChar(15)")]
		public string p_phone_no
		{
			get
			{
				return this._p_phone_no;
			}
			set
			{
				if ((this._p_phone_no != value))
				{
					this._p_phone_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_email", DbType="VarChar(255)")]
		public string p_email
		{
			get
			{
				return this._p_email;
			}
			set
			{
				if ((this._p_email != value))
				{
					this._p_email = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.section")]
	public partial class section : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sec_id;
		
		private int _co_id;
		
		private int _sec_no;
		
		private string _u_name;
		
		private EntityRef<course_offered> _course_offered;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsec_idChanging(int value);
    partial void Onsec_idChanged();
    partial void Onco_idChanging(int value);
    partial void Onco_idChanged();
    partial void Onsec_noChanging(int value);
    partial void Onsec_noChanged();
    partial void Onu_nameChanging(string value);
    partial void Onu_nameChanged();
    #endregion
		
		public section()
		{
			this._course_offered = default(EntityRef<course_offered>);
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sec_id
		{
			get
			{
				return this._sec_id;
			}
			set
			{
				if ((this._sec_id != value))
				{
					this.Onsec_idChanging(value);
					this.SendPropertyChanging();
					this._sec_id = value;
					this.SendPropertyChanged("sec_id");
					this.Onsec_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_id", DbType="Int NOT NULL")]
		public int co_id
		{
			get
			{
				return this._co_id;
			}
			set
			{
				if ((this._co_id != value))
				{
					if (this._course_offered.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onco_idChanging(value);
					this.SendPropertyChanging();
					this._co_id = value;
					this.SendPropertyChanged("co_id");
					this.Onco_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_no", DbType="Int NOT NULL")]
		public int sec_no
		{
			get
			{
				return this._sec_no;
			}
			set
			{
				if ((this._sec_no != value))
				{
					this.Onsec_noChanging(value);
					this.SendPropertyChanging();
					this._sec_no = value;
					this.SendPropertyChanged("sec_no");
					this.Onsec_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onu_nameChanging(value);
					this.SendPropertyChanging();
					this._u_name = value;
					this.SendPropertyChanged("u_name");
					this.Onu_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_offered_section", Storage="_course_offered", ThisKey="co_id", OtherKey="co_id", IsForeignKey=true)]
		public course_offered course_offered
		{
			get
			{
				return this._course_offered.Entity;
			}
			set
			{
				course_offered previousValue = this._course_offered.Entity;
				if (((previousValue != value) 
							|| (this._course_offered.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._course_offered.Entity = null;
						previousValue.sections.Remove(this);
					}
					this._course_offered.Entity = value;
					if ((value != null))
					{
						value.sections.Add(this);
						this._co_id = value.co_id;
					}
					else
					{
						this._co_id = default(int);
					}
					this.SendPropertyChanged("course_offered");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_section", Storage="_user", ThisKey="u_name", OtherKey="u_name", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.sections.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.sections.Add(this);
						this._u_name = value.u_name;
					}
					else
					{
						this._u_name = default(string);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.section_mark")]
	public partial class section_mark : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sm_id;
		
		private int _sec_id;
		
		private string _sm_item;
		
		private double _sm_total;
		
		private double _sm_percentage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsm_idChanging(int value);
    partial void Onsm_idChanged();
    partial void Onsec_idChanging(int value);
    partial void Onsec_idChanged();
    partial void Onsm_itemChanging(string value);
    partial void Onsm_itemChanged();
    partial void Onsm_totalChanging(double value);
    partial void Onsm_totalChanged();
    partial void Onsm_percentageChanging(double value);
    partial void Onsm_percentageChanged();
    #endregion
		
		public section_mark()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sm_id
		{
			get
			{
				return this._sm_id;
			}
			set
			{
				if ((this._sm_id != value))
				{
					this.Onsm_idChanging(value);
					this.SendPropertyChanging();
					this._sm_id = value;
					this.SendPropertyChanged("sm_id");
					this.Onsm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_id", DbType="Int NOT NULL")]
		public int sec_id
		{
			get
			{
				return this._sec_id;
			}
			set
			{
				if ((this._sec_id != value))
				{
					this.Onsec_idChanging(value);
					this.SendPropertyChanging();
					this._sec_id = value;
					this.SendPropertyChanged("sec_id");
					this.Onsec_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_item", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string sm_item
		{
			get
			{
				return this._sm_item;
			}
			set
			{
				if ((this._sm_item != value))
				{
					this.Onsm_itemChanging(value);
					this.SendPropertyChanging();
					this._sm_item = value;
					this.SendPropertyChanged("sm_item");
					this.Onsm_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_total", DbType="Float NOT NULL")]
		public double sm_total
		{
			get
			{
				return this._sm_total;
			}
			set
			{
				if ((this._sm_total != value))
				{
					this.Onsm_totalChanging(value);
					this.SendPropertyChanging();
					this._sm_total = value;
					this.SendPropertyChanged("sm_total");
					this.Onsm_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_percentage", DbType="Float NOT NULL")]
		public double sm_percentage
		{
			get
			{
				return this._sm_percentage;
			}
			set
			{
				if ((this._sm_percentage != value))
				{
					this.Onsm_percentageChanging(value);
					this.SendPropertyChanging();
					this._sm_percentage = value;
					this.SendPropertyChanged("sm_percentage");
					this.Onsm_percentageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.section_student")]
	public partial class section_student
	{
		
		private int _sec_id;
		
		private string _u_name;
		
		public section_student()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_id", DbType="Int NOT NULL")]
		public int sec_id
		{
			get
			{
				return this._sec_id;
			}
			set
			{
				if ((this._sec_id != value))
				{
					this._sec_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this._u_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.semester")]
	public partial class semester : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _s_id;
		
		private string _s_year;
		
		private System.Nullable<int> _s_sem;
		
		private EntitySet<course_offered> _course_offereds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ons_idChanging(int value);
    partial void Ons_idChanged();
    partial void Ons_yearChanging(string value);
    partial void Ons_yearChanged();
    partial void Ons_semChanging(System.Nullable<int> value);
    partial void Ons_semChanged();
    #endregion
		
		public semester()
		{
			this._course_offereds = new EntitySet<course_offered>(new Action<course_offered>(this.attach_course_offereds), new Action<course_offered>(this.detach_course_offereds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int s_id
		{
			get
			{
				return this._s_id;
			}
			set
			{
				if ((this._s_id != value))
				{
					this.Ons_idChanging(value);
					this.SendPropertyChanging();
					this._s_id = value;
					this.SendPropertyChanged("s_id");
					this.Ons_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_year", DbType="VarChar(10)")]
		public string s_year
		{
			get
			{
				return this._s_year;
			}
			set
			{
				if ((this._s_year != value))
				{
					this.Ons_yearChanging(value);
					this.SendPropertyChanging();
					this._s_year = value;
					this.SendPropertyChanged("s_year");
					this.Ons_yearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_sem", DbType="Int")]
		public System.Nullable<int> s_sem
		{
			get
			{
				return this._s_sem;
			}
			set
			{
				if ((this._s_sem != value))
				{
					this.Ons_semChanging(value);
					this.SendPropertyChanging();
					this._s_sem = value;
					this.SendPropertyChanged("s_sem");
					this.Ons_semChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="semester_course_offered", Storage="_course_offereds", ThisKey="s_id", OtherKey="s_id")]
		public EntitySet<course_offered> course_offereds
		{
			get
			{
				return this._course_offereds;
			}
			set
			{
				this._course_offereds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_course_offereds(course_offered entity)
		{
			this.SendPropertyChanging();
			entity.semester = this;
		}
		
		private void detach_course_offereds(course_offered entity)
		{
			this.SendPropertyChanging();
			entity.semester = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student_mark")]
	public partial class student_mark
	{
		
		private string _u_name;
		
		private int _sm_id;
		
		private double _stum_score;
		
		public student_mark()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this._u_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_id", DbType="Int NOT NULL")]
		public int sm_id
		{
			get
			{
				return this._sm_id;
			}
			set
			{
				if ((this._sm_id != value))
				{
					this._sm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stum_score", DbType="Float NOT NULL")]
		public double stum_score
		{
			get
			{
				return this._stum_score;
			}
			set
			{
				if ((this._stum_score != value))
				{
					this._stum_score = value;
				}
			}
		}
	}
	
	public partial class SelectSectionResult
	{
		
		private int _sec_id;
		
		private int _co_id;
		
		private int _sec_no;
		
		private string _u_name;
		
		private int _co_id1;
		
		private int _c_id;
		
		private int _s_id;
		
		private int _c_id1;
		
		private string _c_code;
		
		private string _c_name;
		
		private System.Nullable<int> _c_credit;
		
		private int _s_id1;
		
		private string _s_year;
		
		private System.Nullable<int> _s_sem;
		
		private string _u_name1;
		
		private string _p_name;
		
		private string _p_phone_no;
		
		private string _p_email;
		
		public SelectSectionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_id", DbType="Int NOT NULL")]
		public int sec_id
		{
			get
			{
				return this._sec_id;
			}
			set
			{
				if ((this._sec_id != value))
				{
					this._sec_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_id", DbType="Int NOT NULL")]
		public int co_id
		{
			get
			{
				return this._co_id;
			}
			set
			{
				if ((this._co_id != value))
				{
					this._co_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_no", DbType="Int NOT NULL")]
		public int sec_no
		{
			get
			{
				return this._sec_no;
			}
			set
			{
				if ((this._sec_no != value))
				{
					this._sec_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this._u_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_id1", DbType="Int NOT NULL")]
		public int co_id1
		{
			get
			{
				return this._co_id1;
			}
			set
			{
				if ((this._co_id1 != value))
				{
					this._co_id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int NOT NULL")]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					this._c_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id", DbType="Int NOT NULL")]
		public int s_id
		{
			get
			{
				return this._s_id;
			}
			set
			{
				if ((this._s_id != value))
				{
					this._s_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id1", DbType="Int NOT NULL")]
		public int c_id1
		{
			get
			{
				return this._c_id1;
			}
			set
			{
				if ((this._c_id1 != value))
				{
					this._c_id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_code", DbType="VarChar(10)")]
		public string c_code
		{
			get
			{
				return this._c_code;
			}
			set
			{
				if ((this._c_code != value))
				{
					this._c_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="VarChar(255)")]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this._c_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_credit", DbType="Int")]
		public System.Nullable<int> c_credit
		{
			get
			{
				return this._c_credit;
			}
			set
			{
				if ((this._c_credit != value))
				{
					this._c_credit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id1", DbType="Int NOT NULL")]
		public int s_id1
		{
			get
			{
				return this._s_id1;
			}
			set
			{
				if ((this._s_id1 != value))
				{
					this._s_id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_year", DbType="VarChar(10)")]
		public string s_year
		{
			get
			{
				return this._s_year;
			}
			set
			{
				if ((this._s_year != value))
				{
					this._s_year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_sem", DbType="Int")]
		public System.Nullable<int> s_sem
		{
			get
			{
				return this._s_sem;
			}
			set
			{
				if ((this._s_sem != value))
				{
					this._s_sem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name1", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name1
		{
			get
			{
				return this._u_name1;
			}
			set
			{
				if ((this._u_name1 != value))
				{
					this._u_name1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string p_name
		{
			get
			{
				return this._p_name;
			}
			set
			{
				if ((this._p_name != value))
				{
					this._p_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_phone_no", DbType="VarChar(15)")]
		public string p_phone_no
		{
			get
			{
				return this._p_phone_no;
			}
			set
			{
				if ((this._p_phone_no != value))
				{
					this._p_phone_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_email", DbType="VarChar(255)")]
		public string p_email
		{
			get
			{
				return this._p_email;
			}
			set
			{
				if ((this._p_email != value))
				{
					this._p_email = value;
				}
			}
		}
	}
	
	public partial class SelectCourseOfferedResult
	{
		
		private string _display_name;
		
		private int _c_id;
		
		private string _c_code;
		
		private string _c_name;
		
		private System.Nullable<int> _c_credit;
		
		private int _co_id;
		
		private int _c_id1;
		
		private int _s_id;
		
		private int _s_id1;
		
		private string _s_year;
		
		private System.Nullable<int> _s_sem;
		
		public SelectCourseOfferedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_display_name", DbType="VarChar(266)")]
		public string display_name
		{
			get
			{
				return this._display_name;
			}
			set
			{
				if ((this._display_name != value))
				{
					this._display_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int NOT NULL")]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					this._c_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_code", DbType="VarChar(10)")]
		public string c_code
		{
			get
			{
				return this._c_code;
			}
			set
			{
				if ((this._c_code != value))
				{
					this._c_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="VarChar(255)")]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this._c_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_credit", DbType="Int")]
		public System.Nullable<int> c_credit
		{
			get
			{
				return this._c_credit;
			}
			set
			{
				if ((this._c_credit != value))
				{
					this._c_credit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_id", DbType="Int NOT NULL")]
		public int co_id
		{
			get
			{
				return this._co_id;
			}
			set
			{
				if ((this._co_id != value))
				{
					this._co_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id1", DbType="Int NOT NULL")]
		public int c_id1
		{
			get
			{
				return this._c_id1;
			}
			set
			{
				if ((this._c_id1 != value))
				{
					this._c_id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id", DbType="Int NOT NULL")]
		public int s_id
		{
			get
			{
				return this._s_id;
			}
			set
			{
				if ((this._s_id != value))
				{
					this._s_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id1", DbType="Int NOT NULL")]
		public int s_id1
		{
			get
			{
				return this._s_id1;
			}
			set
			{
				if ((this._s_id1 != value))
				{
					this._s_id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_year", DbType="VarChar(10)")]
		public string s_year
		{
			get
			{
				return this._s_year;
			}
			set
			{
				if ((this._s_year != value))
				{
					this._s_year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_sem", DbType="Int")]
		public System.Nullable<int> s_sem
		{
			get
			{
				return this._s_sem;
			}
			set
			{
				if ((this._s_sem != value))
				{
					this._s_sem = value;
				}
			}
		}
	}
	
	public partial class SelectSectionWithCourseOfferedResult
	{
		
		private string _display_name;
		
		private int _sec_id;
		
		private int _co_id;
		
		private int _sec_no;
		
		private string _u_name;
		
		private int _co_id1;
		
		private int _c_id;
		
		private int _s_id;
		
		private int _c_id1;
		
		private string _c_code;
		
		private string _c_name;
		
		private System.Nullable<int> _c_credit;
		
		private int _s_id1;
		
		private string _s_year;
		
		private System.Nullable<int> _s_sem;
		
		private string _u_name1;
		
		private string _p_name;
		
		private string _p_phone_no;
		
		private string _p_email;
		
		public SelectSectionWithCourseOfferedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_display_name", DbType="VarChar(277)")]
		public string display_name
		{
			get
			{
				return this._display_name;
			}
			set
			{
				if ((this._display_name != value))
				{
					this._display_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_id", DbType="Int NOT NULL")]
		public int sec_id
		{
			get
			{
				return this._sec_id;
			}
			set
			{
				if ((this._sec_id != value))
				{
					this._sec_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_id", DbType="Int NOT NULL")]
		public int co_id
		{
			get
			{
				return this._co_id;
			}
			set
			{
				if ((this._co_id != value))
				{
					this._co_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sec_no", DbType="Int NOT NULL")]
		public int sec_no
		{
			get
			{
				return this._sec_no;
			}
			set
			{
				if ((this._sec_no != value))
				{
					this._sec_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this._u_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_id1", DbType="Int NOT NULL")]
		public int co_id1
		{
			get
			{
				return this._co_id1;
			}
			set
			{
				if ((this._co_id1 != value))
				{
					this._co_id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int NOT NULL")]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					this._c_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id", DbType="Int NOT NULL")]
		public int s_id
		{
			get
			{
				return this._s_id;
			}
			set
			{
				if ((this._s_id != value))
				{
					this._s_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id1", DbType="Int NOT NULL")]
		public int c_id1
		{
			get
			{
				return this._c_id1;
			}
			set
			{
				if ((this._c_id1 != value))
				{
					this._c_id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_code", DbType="VarChar(10)")]
		public string c_code
		{
			get
			{
				return this._c_code;
			}
			set
			{
				if ((this._c_code != value))
				{
					this._c_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="VarChar(255)")]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this._c_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_credit", DbType="Int")]
		public System.Nullable<int> c_credit
		{
			get
			{
				return this._c_credit;
			}
			set
			{
				if ((this._c_credit != value))
				{
					this._c_credit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id1", DbType="Int NOT NULL")]
		public int s_id1
		{
			get
			{
				return this._s_id1;
			}
			set
			{
				if ((this._s_id1 != value))
				{
					this._s_id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_year", DbType="VarChar(10)")]
		public string s_year
		{
			get
			{
				return this._s_year;
			}
			set
			{
				if ((this._s_year != value))
				{
					this._s_year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_sem", DbType="Int")]
		public System.Nullable<int> s_sem
		{
			get
			{
				return this._s_sem;
			}
			set
			{
				if ((this._s_sem != value))
				{
					this._s_sem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name1", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name1
		{
			get
			{
				return this._u_name1;
			}
			set
			{
				if ((this._u_name1 != value))
				{
					this._u_name1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string p_name
		{
			get
			{
				return this._p_name;
			}
			set
			{
				if ((this._p_name != value))
				{
					this._p_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_phone_no", DbType="VarChar(15)")]
		public string p_phone_no
		{
			get
			{
				return this._p_phone_no;
			}
			set
			{
				if ((this._p_phone_no != value))
				{
					this._p_phone_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_email", DbType="VarChar(255)")]
		public string p_email
		{
			get
			{
				return this._p_email;
			}
			set
			{
				if ((this._p_email != value))
				{
					this._p_email = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
