#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="campusweb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertsection_mark(section_mark instance);
    partial void Updatesection_mark(section_mark instance);
    partial void Deletesection_mark(section_mark instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["campuswebConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<student_mark> student_marks
		{
			get
			{
				return this.GetTable<student_mark>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<section_mark> section_marks
		{
			get
			{
				return this.GetTable<section_mark>();
			}
		}
		
		public System.Data.Linq.Table<profile> profiles
		{
			get
			{
				return this.GetTable<profile>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student_mark")]
	public partial class student_mark
	{
		
		private string _u_name;
		
		private int _sm_id;
		
		private double _stum_score;
		
		public student_mark()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this._u_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_id", DbType="Int NOT NULL")]
		public int sm_id
		{
			get
			{
				return this._sm_id;
			}
			set
			{
				if ((this._sm_id != value))
				{
					this._sm_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stum_score", DbType="Float NOT NULL")]
		public double stum_score
		{
			get
			{
				return this._stum_score;
			}
			set
			{
				if ((this._stum_score != value))
				{
					this._stum_score = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _u_name;
		
		private string _u_password;
		
		private string _u_level;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onu_nameChanging(string value);
    partial void Onu_nameChanged();
    partial void Onu_passwordChanging(string value);
    partial void Onu_passwordChanged();
    partial void Onu_levelChanging(string value);
    partial void Onu_levelChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this.Onu_nameChanging(value);
					this.SendPropertyChanging();
					this._u_name = value;
					this.SendPropertyChanged("u_name");
					this.Onu_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string u_password
		{
			get
			{
				return this._u_password;
			}
			set
			{
				if ((this._u_password != value))
				{
					this.Onu_passwordChanging(value);
					this.SendPropertyChanging();
					this._u_password = value;
					this.SendPropertyChanged("u_password");
					this.Onu_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_level", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_level
		{
			get
			{
				return this._u_level;
			}
			set
			{
				if ((this._u_level != value))
				{
					this.Onu_levelChanging(value);
					this.SendPropertyChanging();
					this._u_level = value;
					this.SendPropertyChanged("u_level");
					this.Onu_levelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.section_mark")]
	public partial class section_mark : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sm_id;
		
		private int _s_id;
		
		private string _sm_item;
		
		private double _sm_total;
		
		private double _sm_percentage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsm_idChanging(int value);
    partial void Onsm_idChanged();
    partial void Ons_idChanging(int value);
    partial void Ons_idChanged();
    partial void Onsm_itemChanging(string value);
    partial void Onsm_itemChanged();
    partial void Onsm_totalChanging(double value);
    partial void Onsm_totalChanged();
    partial void Onsm_percentageChanging(double value);
    partial void Onsm_percentageChanged();
    #endregion
		
		public section_mark()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sm_id
		{
			get
			{
				return this._sm_id;
			}
			set
			{
				if ((this._sm_id != value))
				{
					this.Onsm_idChanging(value);
					this.SendPropertyChanging();
					this._sm_id = value;
					this.SendPropertyChanged("sm_id");
					this.Onsm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_id", DbType="Int NOT NULL")]
		public int s_id
		{
			get
			{
				return this._s_id;
			}
			set
			{
				if ((this._s_id != value))
				{
					this.Ons_idChanging(value);
					this.SendPropertyChanging();
					this._s_id = value;
					this.SendPropertyChanged("s_id");
					this.Ons_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_item", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string sm_item
		{
			get
			{
				return this._sm_item;
			}
			set
			{
				if ((this._sm_item != value))
				{
					this.Onsm_itemChanging(value);
					this.SendPropertyChanging();
					this._sm_item = value;
					this.SendPropertyChanged("sm_item");
					this.Onsm_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_total", DbType="Float NOT NULL")]
		public double sm_total
		{
			get
			{
				return this._sm_total;
			}
			set
			{
				if ((this._sm_total != value))
				{
					this.Onsm_totalChanging(value);
					this.SendPropertyChanging();
					this._sm_total = value;
					this.SendPropertyChanged("sm_total");
					this.Onsm_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_percentage", DbType="Float NOT NULL")]
		public double sm_percentage
		{
			get
			{
				return this._sm_percentage;
			}
			set
			{
				if ((this._sm_percentage != value))
				{
					this.Onsm_percentageChanging(value);
					this.SendPropertyChanging();
					this._sm_percentage = value;
					this.SendPropertyChanged("sm_percentage");
					this.Onsm_percentageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.profile")]
	public partial class profile
	{
		
		private string _u_name;
		
		private string _p_name;
		
		private string _p_phone_no;
		
		private string _p_email;
		
		public profile()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this._u_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string p_name
		{
			get
			{
				return this._p_name;
			}
			set
			{
				if ((this._p_name != value))
				{
					this._p_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_phone_no", DbType="VarChar(15)")]
		public string p_phone_no
		{
			get
			{
				return this._p_phone_no;
			}
			set
			{
				if ((this._p_phone_no != value))
				{
					this._p_phone_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_email", DbType="VarChar(255)")]
		public string p_email
		{
			get
			{
				return this._p_email;
			}
			set
			{
				if ((this._p_email != value))
				{
					this._p_email = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
